name = "PlantUML"
grammar = "plantuml"
path_suffixes = ["puml", "plantuml", "pu", "iuml", "wsd"]
line_comments = ["' "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
